Feat/add login
wafflestudio/snutt-webclient-v2 pull request #41
Opened 2022-12-31 10:00 UTC by ars-ki-00

별 건 아니고, `errorTable` 도 repository, service 형식 적용할까요?

2022-12-31 10:05 UTC, woohm402 requested changes
1. 여유 되시면 `errorTable `도 `errorService` 이런 곳으로 옮겨도 좋을거같아요! 뷰보다는 비즈니스 로직이라고 보이네요
2. e2e 테스트 붙어있어야 할 거 같아요
3. `any` 는 없애면 어떨까요?

2023-01-07 12:34 UTC, woohm402 commented
👀

2023-01-14 10:46 UTC, woohm402 requested changes
로그인 실
패 케이스
테스트 케
이스 붙어
있어야 할
것 같아요

2023-01-15 08:07 UTC, ars-ki-00 commented
@woohm402 건든 거 없는데 왜 unit test 페일나죠,,,?

2023-01-16 11:51 UTC, woohm402 commented on e2e/login/login.spec.ts
> +  await expect(page.getByTestId('error-message')).not.toHaveText('');
무슨 값 뜨는지 테스트 필요

2023-01-16 11:51 UTC, woohm402 commented on src/mocks/handlers/index.ts
> +      if (id === 'fail-test-id') {
mocks 에 users 목록 넣어놓고 존재하는지 찾는게 낫지않나?

2023-01-16 11:51 UTC, woohm402 commented on src/repositories/errorRepository.ts
> +      return matchingError ? matchingError.message : useDefaultMessage ? '에러가 발생했습니다' : '';
에러 vs 오류

2023-01-16 11:51 UTC, woohm402 commented on src/utils/errorTable.ts
> +  { code: 12300, message: '강의 시간이 서로 겹칩니다.' },
저도 적용하겠슴다 👍

2023-01-16 11:51 UTC, woohm402 commented on src/repositories/authRepository.ts
> +          'Content-Type': 'application/x-www-form-urlencoded',
얜 뭐예요? `application/json` 만 써봤는디

2023-01-16 11:51 UTC, woohm402 commented on src/pages/login/index.tsx
> +  opacity: 1;
?
```suggestion
```

2023-01-16 11:53 UTC, ars-ki-00 commented on src/repositories/authRepository.ts
> +          'Content-Type': 'application/x-www-form-urlencoded',
기존이 body에 url encode해서 보내던데요,,,?

2023-01-16 11:56 UTC, ars-ki-00 commented on src/repositories/errorRepository.ts
> +      return matchingError ? matchingError.message : useDefaultMessage ? '에러가 발생했습니다' : '';
흠 🤔

2023-01-16 11:56 UTC, ars-ki-00 commented on src/mocks/handlers/index.ts
> +      if (id === 'fail-test-id') {
옹,,, 인정

2023-01-16 12:08 UTC, ars-ki-00 commented on src/repositories/errorRepository.ts
> +      return matchingError ? matchingError.message : useDefaultMessage ? '에러가 발생했습니다' : '';
머로할까ㅣ요

2023-01-16 12:09 UTC, ars-ki-00 commented on src/pages/login/index.tsx
> +  opacity: 1;
무지성 복붙

2023-01-16 12:29 UTC, woohm402 approved these changes

2023-01-16 12:30 UTC, merged